FORMAT: 1A
HOST: http://mnemonic-iot-app.apiblueprint.org/

# mnemonic-iot-app

## Room Door [/requestPass?documentKey=ROOM42-HOTEL-MARAVILLAS&address=0x627306090abaB3A6e1400e9345bC60c78a8BEf57]

### Request pass to room [GET]

+ Response 200 (application/json)
    {
        "Granted": true
    }